import apple from "./apple.png"
import folder from "./folder.png"
import disk from "./disk.png"
import search from "./search.png"
import correct from "./correct.png"
import close from "./close.png"
import file_explorer from "./file_explorer.png"
import github from "./github.png"
import del_icon from "./delete.png"
import show_property from "./show_property.png"
export {apple,folder,disk,search,correct,close,file_explorer,github,del_icon,show_property}