import folder from "./folder.png"
import disk from "./disk.png"
import correct from "./correct.png"
import close from "./close.png"
import file_explorer from "./file_explorer.png"
import github from "./github.png"
import del_icon from "./delete.png"
import show_property from "./show_property.png"
import back from "./back.png"
import heart from "./heart.svg"
import skull from "./skull.svg"
import png from "./png.png"
import pdf from "./pdf.png"
import txt from "./txt.png"
import user from "./user.png"
import jpg from "./jpg.png"
import file from "./file.png"
export {file,user,back,heart,skull,folder,disk,correct,close,file_explorer,github,del_icon,show_property,png,pdf,txt,jpg}